# Netlify configuration file

[build]
  command = "npm run build"
  publish = ".next"

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

# For Next.js Image Optimization
[[plugins]]
  package = "@netlify/plugin-nextjs"
